/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import Estructuras.Cronometro;

/**
 *
 * @author Antonella
 */
public class Barra extends javax.swing.JPanel {
    private Cronometro cronometro;
    
    public Barra() {
        initComponents();
        cronometro= new Cronometro();
        
        Thread hilo= new Thread(() ->{
            while (true){
                int minutos = cronometro.obtenerMinutos();
                int segundos = cronometro.obtenerSegundos();
                int milisegundos = cronometro.obtenerMilisegundos(); 
                
                timer.setText(String.format("%02d:%02d:%03d", minutos, segundos, milisegundos));
            
            try {
                    Thread.sleep(100);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            
            }
         });
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer = new javax.swing.JLabel();

        timer.setBackground(new java.awt.Color(51, 51, 51));
        timer.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14)); // NOI18N
        timer.setText("00:00:000");
        timer.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        timer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timer, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
