/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import interfaces.GestionDoc.Documentos;
import interfaces.Usuario.Usuarios;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Antonella
 */
public class Menu extends javax.swing.JFrame {
    
    /**
     * Creates new form Menu
     */
    public Menu() {
         initComponents();
         
         CronometroInter cronomet=new CronometroInter();
         cronomet.setVisible(true);
         cronomet.StartReloj();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        menu = new FondoPanel();
        documentos = new javax.swing.JButton();
        usuarios = new javax.swing.JButton();
        colaimpresion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        documentos.setBackground(new java.awt.Color(204, 204, 255));
        documentos.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        documentos.setForeground(new java.awt.Color(102, 102, 102));
        documentos.setText("Documentos");
        documentos.setBorderPainted(false);
        documentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentosActionPerformed(evt);
            }
        });
        menu.add(documentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 280, 50));

        usuarios.setBackground(new java.awt.Color(204, 204, 255));
        usuarios.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(102, 102, 102));
        usuarios.setText("Usuarios");
        usuarios.setBorderPainted(false);
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        menu.add(usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 280, 50));

        colaimpresion.setBackground(new java.awt.Color(204, 204, 255));
        colaimpresion.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        colaimpresion.setForeground(new java.awt.Color(102, 102, 102));
        colaimpresion.setText("Monticulo Binario");
        colaimpresion.setBorderPainted(false);
        colaimpresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colaimpresionActionPerformed(evt);
            }
        });
        menu.add(colaimpresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 280, 50));

        jLabel1.setFont(new java.awt.Font("Vineta BT", 0, 18)); // NOI18N
        jLabel1.setText("Menu");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        // TODO add your handling code here:
        new Usuarios().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_usuariosActionPerformed

    private void documentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentosActionPerformed
        // TODO add your handling code here:
        new Documentos().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_documentosActionPerformed

    private void colaimpresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colaimpresionActionPerformed
        // TODO add your handling code here:
        new ColaImpresion().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_colaimpresionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton colaimpresion;
    private javax.swing.JButton documentos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel menu;
    private java.awt.Panel panel1;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables

   
    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen= new ImageIcon(getClass().getResource("/imagenes/fondo.jpg")).getImage();
            g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
                    setOpaque(false);
                    
                    super.paint(g);
        }
    }}
